import org.gradle.jvm.toolchain.JavaLanguageVersion

plugins {
    id 'java'
    id 'idea'
    id 'org.springframework.boot' version '2.7.18'
}

apply from: '../../dependencyDefinitions.gradle'
apply from: '../sandboxDefaults.gradle'

wrapper {
	gradleVersion = '8.13'
	distributionType = Wrapper.DistributionType.ALL
	// TODO:
	// MacAppBundle
}

/*
class ConfigurationDetectionDependencyResolutionListener
        implements DependencyResolutionListener, BuildListener {
    private final Logger logger
    private boolean enabled = true
    private final Map<String, Long> timestampMap = [:]
    private final Map<String, Long> resultMap = [:]
    private final java.util.concurrent.locks.Lock lock =
        new java.util.concurrent.locks.ReentrantLock()

    ConfigurationDetectionDependencyResolutionListener(Gradle gradle) {
        logger = gradle.rootProject.logger
    }
    
    // DependencyResolutionListener
    void beforeResolve(ResolvableDependencies dependencies) {
        def path = dependencies.path
        lock.lock()
        try {
            timestampMap[path] = System.currentTimeMillis()
        } finally {
            lock.unlock()
        }
    }

    void afterResolve(ResolvableDependencies dependencies) {
        def path = dependencies.path
        long millis
        lock.lock()
        try {
            if(!enabled) {
                return
            }
    
            millis = System.currentTimeMillis() - timestampMap[path]
            resultMap[path] = millis
        } finally {
            lock.unlock()
        }

        logger.warn('PERFORMANCE WARNING: Resolving {} during configuration took {}ms!',path, millis, new Throwable())
    }

    // BuildListener
    void buildStarted(Gradle gradle) {
    }

    void settingsEvaluated(Settings settings) {
    }

    void projectsLoaded(Gradle gradle) {
    }

    void projectsEvaluated(Gradle gradle) {
        long accumulated = 0
        lock.lock()
        try {
            enabled = false
            if(resultMap.isEmpty()) {
                return
            }
    
            resultMap.each {
                accumulated += it.value
            }
            timestampMap.clear()
            resultMap.clear()
        } finally {
            lock.unlock()
        }

        logger.warn('### Total time spent resolving dependencies during configuration:\n### {}ms', accumulated)
    }

    void buildFinished(BuildResult result) {
    }
}

gradle.addListener(new ConfigurationDetectionDependencyResolutionListener(gradle))
*/

version = '1.0.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web:2.7.18'
	runtimeOnly "de.huxhorn.lilith:de.huxhorn.lilith.logback.appender.multiplex-access:${lilithVersion}"
	runtimeOnly "de.huxhorn.lilith:de.huxhorn.lilith.logback.appender.multiplex-classic:${lilithVersion}"
	runtimeOnly "de.huxhorn.lilith:de.huxhorn.lilith.logback.encoder.access:${lilithVersion}"
	runtimeOnly "de.huxhorn.lilith:de.huxhorn.lilith.logback.encoder.classic:${lilithVersion}"
	runtimeOnly libraries.'spring-boot-ext-logback-access'
	implementation libraries.'logback-access'
	implementation libraries.'logback-core'
	implementation libraries.'logback-classic'
	testImplementation 'org.springframework.boot:spring-boot-starter-test:2.7.18'
}
